version: 1.2
service:
  type: docker-compose
  name: A cool service
  author: Andrew Duncan
  description: |
    This is the coolest service,
    it is very cool.
  files:
     - docker-compose.yml 
     - README.md
